assembly_info:
  patch: false

platform:
  - Any CPU

configuration:
  - Release

build_script:
  - powershell .\build.ps1

test: off
skip_tags: true

cache:
  - src\packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
