//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestStack.BDDfy.Reporters.Html {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HtmlReportResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal HtmlReportResources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestStack.BDDfy.HtmlReportResources", typeof(HtmlReportResources).Assembly());
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  body{margin:0;padding:0;padding-bottom:40px;max-width:100%;background-color:#fff;font-size:10pt;font-family:Verdana,Arial,Helvetica,sans-serif}ul{margin:5px;padding:5px;border:1px solid #d0d0d0;-ms-border-radius:10px;border-radius:10px;background-color:#f0f0f0}li{list-style-type:none}#main{width:100%;height:100%}.header,.footer{background:#679bdb;background:-moz-linear-gradient(top,#679bdb 1%,#3b77a5 100%);background:-ms-linear-gradient(top,#679bdb 1%,#3b77a5 100%);background:-o-linear-gradient(top,#679bdb  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string classic_css_min {
            get {
                return ResourceManager.GetString("classic_css_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  $(function(){$(&quot;.canToggle&quot;).each(function(){var n=$(&quot;#&quot;+$(this).data(&quot;toggle-target&quot;));n.hide();$(this).click(function(){n.toggle(200)})});$(&quot;.expandAll&quot;).click(function(){$(&quot;.steps&quot;).css(&quot;display&quot;,&quot;&quot;)});$(&quot;.collapseAll&quot;).click(function(){$(&quot;.steps&quot;).css(&quot;display&quot;,&quot;none&quot;)});$(&quot;ul.resultSummary li:not(&apos;.storySummary&apos;):not(&apos;.scenarioSummary&apos;)&quot;).append(&quot;&lt;input type=&apos;checkbox&apos; class=&apos;cbx_toggle&apos; checked/&gt;&quot;);$(&quot;.cbx_toggle&quot;).click(function(){var n=$(this),t=n.closest(&quot;li&quot;).attr(&quot;class&quot;);$(&quot;#testResult div.scena [rest of string was truncated]&quot;;.
        /// </summary>
        public static string classic_js_min {
            get {
                return ResourceManager.GetString("classic_js_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to If you drop a custom Javascript named BDDfyCustom.js in your output folder it gets embedded here. This way you can apply some custom Javascript logic to your html report..
        /// </summary>
        public static string CustomJavascriptComment {
            get {
                return ResourceManager.GetString("CustomJavascriptComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to If you drop a custom stylesheet named BDDfyCustom.css in your output folder it gets embedded here. This way you can apply some custom styles over your html report..
        /// </summary>
        public static string CustomStylesheetComment {
            get {
                return ResourceManager.GetString("CustomStylesheetComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  /*! jQuery v2.1.0 | (c) 2005, 2014 jQuery Foundation, Inc. | jquery.org/license */
        ///!function(a,b){&quot;object&quot;==typeof module&amp;&amp;&quot;object&quot;==typeof module.exports?module.exports=a.document?b(a,!0):function(a){if(!a.document)throw new Error(&quot;jQuery requires a window with a document&quot;);return b(a)}:b(a)}(&quot;undefined&quot;!=typeof window?window:this,function(a,b){var c=[],d=c.slice,e=c.concat,f=c.push,g=c.indexOf,h={},i=h.toString,j=h.hasOwnProperty,k=&quot;&quot;.trim,l={},m=a.document,n=&quot;2.1.0&quot;,o=function(a,b){return new o.fn.init( [rest of string was truncated]&quot;;.
        /// </summary>
        public static string jquery_2_1_0_min {
            get {
                return ResourceManager.GetString("jquery_2_1_0_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  html,body,div,span,applet,object,iframe,h1,h2,h3,h4,h5,h6,p,blockquote,pre,a,abbr,acronym,address,big,cite,code,del,dfn,em,img,ins,kbd,q,s,samp,small,strike,strong,sub,sup,tt,var,b,u,i,center,dl,dt,dd,ol,ul,li,fieldset,form,label,legend,table,caption,tbody,tfoot,thead,tr,th,td,article,aside,canvas,details,embed,figure,figcaption,footer,header,hgroup,menu,nav,output,ruby,section,summary,time,mark,audio,video{margin:0;padding:0;border:0;font-size:100%;font:inherit;vertical-align:baseline}article,aside,details [rest of string was truncated]&quot;;.
        /// </summary>
        public static string metro_css_min {
            get {
                return ResourceManager.GetString("metro_css_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  $(function(){$(&quot;.canToggle&quot;).each(function(){var n=$(&quot;#&quot;+$(this).data(&quot;toggle-target&quot;));n.hide();$(this).click(function(){n.toggle(200)})});$(&quot;.expandAll&quot;).click(function(){$(&quot;.steps&quot;).css(&quot;display&quot;,&quot;&quot;)});$(&quot;.collapseAll&quot;).click(function(){$(&quot;.steps&quot;).css(&quot;display&quot;,&quot;none&quot;)});$(&quot;#filterOptions a&quot;).click(function(){var n=$(this).children(&quot;div&quot;),t,i;n.toggleClass(&quot;filterTileDisabled&quot;);t=!n.hasClass(&quot;filterTileDisabled&quot;);i=n.data(&quot;target-class&quot;);$(&quot;div.&quot;+i).closest(&quot;.scenario&quot;).toggle(t)})});
        ////*
        /////# sourceMap [rest of string was truncated]&quot;;.
        /// </summary>
        public static string metro_js_min {
            get {
                return ResourceManager.GetString("metro_js_min", resourceCulture);
            }
        }
    }
}
