using TestStack.BDDfy.Reporters.Writers;

namespace TestStack.BDDfy.Reporters.Html
{
    public class ReportConfiguration(string outputFileName)
    {
        public string OutputFileName { get; set; } = outputFileName;
        public string? OutputPath { get; set; }
        public string ReportHeader { get; set; } = "BDDfy Report";
        public string ReportDescription { get; set; } = "Report generated by TestStack.BDDfy";
        public IFileWriter FileWriter { get; set; } = new FileWriter();
        public virtual bool RunsOn(Story story) => true;
    }

    public class ReportConfiguration<TReportBuilder>(string outputFileName)
        : ReportConfiguration(outputFileName) where TReportBuilder 
        : IReportBuilder, new()
    {
        public IReportBuilder ReportBuilder { get; set; } = new TReportBuilder();
    }
}