//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestStack.BDDfy.Reporters.Html {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HtmlReportResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HtmlReportResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestStack.BDDfy.Reporters.Html.HtmlReportResources", typeof(HtmlReportResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body
        ///{
        ///	max-width:100%;
        ///	background-color:#fff;
        ///	font-family: Verdana, Arial, Helvetica, sans-serif;
        ///	font-size: 10pt;
        ///	margin: 0;
        ///	padding: 0;
        ///    padding-bottom:40px;
        ///}
        ///
        ///ul
        ///{
        ///    padding:5px;
        ///    margin:5px;
        ///    border:1px solid #d0d0d0;
        ///    background-color:#f0f0f0;
        ///    -webkit-border-radius: 10px;
        ///    -moz-border-radius:    10px;
        ///    border-radius:10px;
        ///}
        ///
        ///li
        ///{
        ///    list-style-type: none;
        ///}
        ///			
        ///#main
        ///{
        ///	width: 100%;
        ///	height:100%;
        ///}
        ///			
        ///.header, .footer
        ///{
        ///    background: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BDDfy_css {
            get {
                return ResourceManager.GetString("BDDfy_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $(function () {
        ///    $(&apos;.canToggle&apos;).each(function () {
        ///        var target = $(&apos;#&apos; + $(this).data(&apos;toggle-target&apos;));
        ///        target.hide();
        ///        $(this).click(function () {
        ///            target.toggle(200);
        ///        });
        ///    });
        ///
        ///    $(&apos;.expandAll&apos;).click(function () {
        ///        $(&apos;.steps&apos;).css(&apos;display&apos;, &apos;&apos;);
        ///    });
        ///    $(&apos;.collapseAll&apos;).click(function () {
        ///        $(&apos;.steps&apos;).css(&apos;display&apos;, &apos;none&apos;);
        ///    });
        ///
        ///    $(&quot;ul.resultSummary li:not(&apos;.storySummary&apos;):not(&apos;.scenarioSummary&apos;)&quot;)
        ///        .a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BDDfy_js {
            get {
                return ResourceManager.GetString("BDDfy_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you drop a custom Javascript named BDDfyCustom.js in your output folder it gets embedded here. This way you can apply some custom Javascript logic to your html report..
        /// </summary>
        internal static string CustomJavascriptComment {
            get {
                return ResourceManager.GetString("CustomJavascriptComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you drop a custom stylesheet named BDDfyCustom.css in your output folder it gets embedded here. This way you can apply some custom styles over your html report..
        /// </summary>
        internal static string CustomStylesheetComment {
            get {
                return ResourceManager.GetString("CustomStylesheetComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! jQuery v2.1.0 | (c) 2005, 2014 jQuery Foundation, Inc. | jquery.org/license */
        ///!function(a,b){&quot;object&quot;==typeof module&amp;&amp;&quot;object&quot;==typeof module.exports?module.exports=a.document?b(a,!0):function(a){if(!a.document)throw new Error(&quot;jQuery requires a window with a document&quot;);return b(a)}:b(a)}(&quot;undefined&quot;!=typeof window?window:this,function(a,b){var c=[],d=c.slice,e=c.concat,f=c.push,g=c.indexOf,h={},i=h.toString,j=h.hasOwnProperty,k=&quot;&quot;.trim,l={},m=a.document,n=&quot;2.1.0&quot;,o=function(a,b){return new o.fn.init(a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_2_1_0_min {
            get {
                return ResourceManager.GetString("jquery_2_1_0_min", resourceCulture);
            }
        }
    }
}
